apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xynafactoryservices.xyna.com
spec:
  group: xyna.com
  names:
    kind: XynaFactoryService
    plural: xynafactoryservices
    singular: xynafactoryservice
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image: { type: string }
                replicas: { type: integer }
                applications:
                  type: array
                  items:
                    type: object
                    properties:
                      order: { type: integer }
                      name: { type: string }
                      appUrl: { type: string }
                servicePorts:
                  type: array
                  items:
                    type: object
                    properties:
                      #ingressPrefix: {type: string}
                      serviceName: { type: string }
                      port: { type: integer }
                      targetPort: { type: integer }
                      protocol: { type: string }