apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xynafactoryservices.xyna.com
spec:
  group: xyna.com
  names:
    kind: XynaFactoryService
    plural: xynafactoryservices
    singular: xynafactoryservice
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image: { type: string }
                replicas: { type: integer }
                applications:
                  type: array
                  description: |
                    list of xyna-applications, that make up the microservice
                    The Xyna-Application-package hast to be accessibla via the appUrl from inside the cluster.
                    The property 'order' defines the order of import of applications in case of dependencies (lower numbers are imported earlier).
                  items:
                    type: object
                    properties:
                      order: { type: integer }
                      name: { type: string }
                      appUrl: { type: string }
                servicePorts:
                  type: array
                  description: |
                    definition of one or more services for which resources ar created for the microservice
                  items:
                    type: object
                    properties:
                      #ingressPrefix: {type: string}
                      serviceName: { type: string }
                      port: { type: integer }
                      targetPort: { type: integer }
                      protocol: { type: string }
                nodeLabels:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                  description: List of node label key-value pairs for node affinity